# Generated by Django 5.0.3 on 2024-03-28 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustoAquisicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frete', models.FloatField()),
                ('hospedagem', models.FloatField()),
                ('alimento', models.FloatField()),
                ('luz', models.FloatField()),
                ('internet', models.FloatField()),
                ('sacola', models.FloatField()),
                ('aluguel', models.FloatField()),
                ('trafego_pago', models.FloatField()),
                ('salario', models.FloatField()),
                ('taxa_cartao', models.FloatField()),
                ('ICMS', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MargemLucro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('praia', models.FloatField()),
                ('casual', models.FloatField()),
                ('intima', models.FloatField()),
                ('fitness', models.FloatField()),
                ('jeans', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.IntegerField()),
                ('descricao', models.CharField(max_length=200)),
                ('valor_aquisicao', models.FloatField()),
                ('fornecedor', models.CharField(max_length=100)),
                ('margem_lucro', models.FloatField()),
            ],
        ),
    ]
