# Generated by Django 5.0.3 on 2024-03-29 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_produto_quantidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='custoaquisicao',
            name='CA',
            field=models.FloatField(default=0),
        ),
    ]
