# Generated by Django 5.0.3 on 2024-03-29 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_alter_custoaquisicao_ca_alter_custoaquisicao_icms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='custoaquisicao',
            name='custo_venda',
            field=models.FloatField(default=0),
        ),
    ]
