# Generated by Django 5.0.3 on 2024-03-29 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_custoaquisicao_custo_venda'),
    ]

    operations = [
        migrations.AddField(
            model_name='custoaquisicao',
            name='total_adquirido_revenda',
            field=models.FloatField(default=0),
        ),
    ]
