# Generated by Django 5.0.3 on 2024-03-30 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_alter_produto_margem_lucro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(max_length=50)),
                ('cliente', models.CharField(max_length=150)),
                ('tamanho', models.CharField(max_length=5)),
                ('preco', models.FloatField(default=0)),
                ('quantidade', models.IntegerField(default=1)),
            ],
        ),
    ]
