# Generated by Django 5.0.3 on 2024-03-30 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_vendas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(max_length=50)),
                ('cliente', models.CharField(max_length=150)),
                ('tamanho', models.CharField(max_length=5)),
                ('preco', models.FloatField(default=0)),
                ('quantidade', models.IntegerField(default=1)),
                ('parcelas', models.IntegerField(default=0)),
                ('desconto', models.FloatField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Vendas',
        ),
    ]
