# Generated by Django 5.0.3 on 2024-03-30 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_venda_delete_vendas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venda',
            old_name='preco',
            new_name='valor',
        ),
        migrations.AddField(
            model_name='venda',
            name='descricao',
            field=models.CharField(default='', max_length=200),
        ),
    ]
