# Generated by Django 5.0.3 on 2024-03-30 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_rename_preco_venda_valor_venda_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='descricao',
            field=models.CharField(max_length=200),
        ),
    ]
